CREATE TABLE IF NOT EXISTS Pelanggan (
  pelangganId VARCHAR(10) PRIMARY KEY,
  noTelefon VARCHAR(15) NOT NULL UNIQUE,
  nama VARCHAR(100) NOT NULL,
  alamat VARCHAR(500),
  tarikhDaftar DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
