CREATE TABLE IF NOT EXISTS Peniaga (
  peniagaId INT AUTO_INCREMENT PRIMARY KEY,
  namaPenggunaAdmin VARCHAR(50) NOT NULL UNIQUE,
  kataLaluan VARCHAR(255) NOT NULL,
  namaKedai VARCHAR(100),
  noTelefonKedai VARCHAR(15),
  peneranganKedai VARCHAR(500),
  tarikhKemaskini DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
