CREATE TABLE IF NOT EXISTS KategoriSpesifikasiKek (
  kategoriId INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  penerangan VARCHAR(500),
  aktif BOOLEAN NOT NULL DEFAULT TRUE,
  tarikhCipta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
