CREATE TABLE IF NOT EXISTS PilihanSpesifikasiKek (
  pilihanId VARCHAR(10) PRIMARY KEY,
  kategoriId VARCHAR(10) NOT NULL,
  nama VARCHAR(100) NOT NULL,
  penerangan VARCHAR(500),
  hargaTambahan DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  aktif BOOLEAN NOT NULL DEFAULT TRUE,
  tarikhCipta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pilihan_kategori FOREIGN KEY (kategoriId) REFERENCES KategoriSpesifikasiKek(kategoriId) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
