CREATE TABLE IF NOT EXISTS ImejTempahan (
  imejId VARCHAR(10) PRIMARY KEY,
  tempahanId VARCHAR(10) NOT NULL,
  jenisImej ENUM('AI','Muat Naik') NOT NULL,
  urlImej VARCHAR(500) NOT NULL,
  promptAI VARCHAR(500),
  tarikhMuatNaik DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_imej_tempahan FOREIGN KEY (tempahanId) REFERENCES Tempahan(tempahanId) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
