CREATE TABLE IF NOT EXISTS TarikhTutup (
  tarikhTutupId VARCHAR(10) PRIMARY KEY,
  tarikh DATE NOT NULL UNIQUE,
  catatan VARCHAR(200),
  tarikhCipta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
